"""
Quality and heuristic filters for CodeScribe Data Cleanser.
"""

import re
import logging
from typing import Optional

logger = logging.getLogger("CodeScribe.Cleanser.Heuristics")

class QualityFilter:
    """Applies heuristic checks to filter out low-quality code or boilerplate."""

    def __init__(
        self,
        min_size: int = 20,          # bytes
        max_size: int = 1024 * 1024, # 1MB
        max_line_length: int = 1000,
        min_alpha_ratio: float = 0.5
    ):
        self.min_size = min_size
        self.max_size = max_size
        self.max_line_length = max_line_length
        self.min_alpha_ratio = min_alpha_ratio
        
        # Patterns for auto-generated code
        self.autogen_patterns = [
            re.compile(r"(?i)do not edit"),
            re.compile(r"(?i)auto-generated"),
            re.compile(r"(?i)generated by"),
            re.compile(r"(?i)this file is generated"),
        ]

    def is_auto_generated(self, content: str) -> bool:
        """Check if the first few lines contain auto-generated markers."""
        # Check only the first 1000 characters to be fast
        header = content[:1000]
        for pattern in self.autogen_patterns:
            if pattern.search(header):
                return True
        return False

    def is_high_quality(self, content: str) -> bool:
        """
        Main heuristic check for file content.
        Returns True if the content passes all quality checks.
        """
        size = len(content)
        if size < self.min_size or size > self.max_size:
            return False

        if self.is_auto_generated(content):
            return False

        lines = content.splitlines()
        if not lines:
            return False

        # Check for minified code or excessive line lengths
        max_len = max(len(line) for line in lines)
        if max_len > self.max_line_length:
            return False

        # Check alphanumeric ratio (filters out heavy binary-like text or excessive punctuation)
        alnum_count = sum(1 for c in content if c.isalnum() or c.isspace())
        if alnum_count / size < self.min_alpha_ratio:
            return False

        return True
