"""
templates.py -- Markdown Templates for Documentation Generation.

Provides structured text templates that transform parsed and analyzed
code data into clean, human-readable Markdown documentation. Each
template function receives typed data and returns formatted strings.

This module acts as the "NLP layer" -- it handles all natural language
construction, phrasing decisions, and document formatting. By
centralizing text generation here, the main generator engine stays
focused on orchestration.

Design Note:
    Templates use Python's built-in string formatting rather than
    external template engines (Jinja2, etc.) to keep the project
    dependency-free. If a more powerful template engine is needed
    in the future, only this module needs to change.
"""

from __future__ import annotations

from typing import Optional

from src.parser.base import (
    ClassInfo,
    FunctionInfo,
    ImportInfo,
    MethodInfo,
    ModuleInfo,
    Parameter,
    Visibility,
)
from src.analyzer.models import (
    AnalysisResult,
    CodebaseStats,
    DependencyEdge,
    InheritanceNode,
    ModuleMetrics,
)


# ---------------------------------------------------------------------------
# Text Helpers
# ---------------------------------------------------------------------------


def _visibility_badge(visibility: Visibility) -> str:
    """Return a short label for a visibility level.

    Args:
        visibility: The Visibility enum value.

    Returns:
        A formatted string like "(public)", "(private)", etc.
    """
    return "({})".format(visibility.value)


def _format_param_signature(params: list[Parameter]) -> str:
    """Format a parameter list into a function signature string.

    Args:
        params: Ordered list of Parameter objects.

    Returns:
        A string like "x: int, y: str = 'hello'" or "()" if empty.
    """
    if not params:
        return "()"
    parts = []
    for p in params:
        s = p.name
        if p.type_hint:
            s += ": {}".format(p.type_hint)
        if p.default_value:
            s += " = {}".format(p.default_value)
        parts.append(s)
    return "({})".format(", ".join(parts))


def _format_decorators(decorators: list[str]) -> str:
    """Format a list of decorators as prefixed lines.

    Args:
        decorators: List of decorator name strings.

    Returns:
        Formatted decorator lines or empty string.
    """
    if not decorators:
        return ""
    lines = ["@{}".format(d) for d in decorators]
    return "\n".join(lines) + "\n"


def _docstring_summary(docstring: Optional[str]) -> str:
    """Extract the first line of a docstring as a summary.

    Args:
        docstring: The full docstring text, or None.

    Returns:
        The first non-empty line, or "No description provided."
    """
    if not docstring:
        return "No description provided."
    for line in docstring.strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return "No description provided."


def _indent(text: str, level: int = 1) -> str:
    """Indent every line of text by the given number of levels.

    Args:
        text: The text to indent.
        level: Number of indentation levels (each = 4 spaces).

    Returns:
        The indented text.
    """
    prefix = "    " * level
    return "\n".join(prefix + line for line in text.splitlines())


# ---------------------------------------------------------------------------
# Document Section Templates
# ---------------------------------------------------------------------------


def render_project_header(
    project_name: str,
    stats: CodebaseStats,
    language: str,
) -> str:
    """Render the top-level project documentation header.

    Args:
        project_name: Name of the project.
        stats: Codebase-wide statistics.
        language: Primary language of the codebase.

    Returns:
        Formatted markdown string for the project header section.
    """
    lines = [
        "# {} -- API Documentation".format(project_name),
        "",
        "> Auto-generated by CodeScribe",
        "",
        "## Project Overview",
        "",
        "| Metric | Value |",
        "|---|---|",
        "| Language | {} |".format(language.capitalize()),
        "| Total Modules | {} |".format(stats.total_modules),
        "| Total Functions | {} |".format(stats.total_functions),
        "| Total Classes | {} |".format(stats.total_classes),
        "| Total Methods | {} |".format(stats.total_methods),
        "| Estimated Lines | {} |".format(stats.total_lines),
        "| Documentation Coverage | {:.0%} |".format(stats.overall_doc_coverage),
        "",
    ]

    if stats.most_complex_module:
        lines.append(
            "**Most complex module**: `{}`".format(stats.most_complex_module)
        )
    if stats.most_depended_on:
        lines.append(
            "**Most depended-on module**: `{}`".format(stats.most_depended_on)
        )
    lines.append("")

    return "\n".join(lines)


def render_table_of_contents(modules: list[ModuleInfo]) -> str:
    """Render a table of contents linking to each module section.

    Args:
        modules: List of parsed modules.

    Returns:
        Formatted markdown TOC.
    """
    lines = [
        "## Table of Contents",
        "",
    ]
    for mod in modules:
        name = mod.file_path.name
        anchor = name.lower().replace(".", "").replace("_", "-")
        lines.append("- [{}](#{})".format(name, anchor))
    lines.append("")
    return "\n".join(lines)


def render_module_section(mod: ModuleInfo, metrics: Optional[ModuleMetrics] = None) -> str:
    """Render the full documentation section for a single module.

    Args:
        mod: The parsed module data.
        metrics: Optional metrics for this module.

    Returns:
        Formatted markdown for the module.
    """
    name = mod.file_path.name
    lines = [
        "---",
        "",
        "## `{}`".format(name),
        "",
    ]

    # Module docstring
    if mod.module_docstring:
        lines.append(mod.module_docstring.strip())
        lines.append("")

    # Metrics summary table
    if metrics:
        lines.extend([
            "### Module Statistics",
            "",
            "| Metric | Value |",
            "|---|---|",
            "| Functions | {} |".format(metrics.num_functions),
            "| Classes | {} |".format(metrics.num_classes),
            "| Methods | {} |".format(metrics.num_methods),
            "| Imports | {} |".format(metrics.num_imports),
            "| Lines | {} |".format(metrics.total_lines),
            "| Doc Coverage | {:.0%} |".format(metrics.documentation_coverage),
            "",
        ])

    # Imports
    if mod.imports:
        lines.append("### Imports")
        lines.append("")
        lines.append("```python")
        for imp in mod.imports:
            lines.append(_render_import_line(imp))
        lines.append("```")
        lines.append("")

    # Global variables
    if mod.global_variables:
        lines.append("### Module-Level Variables")
        lines.append("")
        for var in mod.global_variables:
            lines.append("- `{}`".format(var))
        lines.append("")

    # Functions
    if mod.functions:
        lines.append("### Functions")
        lines.append("")
        for func in mod.functions:
            lines.append(render_function(func))

    # Classes
    if mod.classes:
        lines.append("### Classes")
        lines.append("")
        for cls in mod.classes:
            lines.append(render_class(cls))

    return "\n".join(lines)


def _render_import_line(imp: ImportInfo) -> str:
    """Render a single import statement.

    Args:
        imp: The import info.

    Returns:
        A Python import statement string.
    """
    if imp.names:
        names = ", ".join(imp.names)
        return "from {} import {}".format(imp.module, names)
    alias = " as {}".format(imp.alias) if imp.alias else ""
    return "import {}{}".format(imp.module, alias)


def render_function(func: FunctionInfo) -> str:
    """Render documentation for a single function.

    Produces a heading, signature, description, parameter table,
    and return type information.

    Args:
        func: The function info.

    Returns:
        Formatted markdown for the function.
    """
    sig = _format_param_signature(func.parameters)
    ret = " -> {}".format(func.return_type) if func.return_type else ""

    lines = [
        "#### `{}`".format(func.name),
        "",
        "```",
    ]

    # Decorators
    if func.decorators:
        for dec in func.decorators:
            lines.append("@{}".format(dec))

    lines.append("{}{}{}".format(func.name, sig, ret))
    lines.append("```")
    lines.append("")

    # Visibility
    lines.append("{} | Lines {}-{}".format(
        _visibility_badge(func.visibility),
        func.start_line,
        func.end_line,
    ))
    lines.append("")

    # Description
    lines.append(_docstring_summary(func.docstring))
    lines.append("")

    # Full docstring details (if longer than one line)
    if func.docstring and len(func.docstring.strip().splitlines()) > 1:
        lines.append("<details>")
        lines.append("<summary>Full Documentation</summary>")
        lines.append("")
        lines.append("```")
        lines.append(func.docstring.strip())
        lines.append("```")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Parameter table
    if func.parameters:
        lines.append("**Parameters:**")
        lines.append("")
        lines.append("| Name | Type | Default |")
        lines.append("|---|---|---|")
        for p in func.parameters:
            type_str = "`{}`".format(p.type_hint) if p.type_hint else "-"
            default_str = "`{}`".format(p.default_value) if p.default_value else "-"
            lines.append("| `{}` | {} | {} |".format(p.name, type_str, default_str))
        lines.append("")

    # Return type
    if func.return_type:
        lines.append("**Returns:** `{}`".format(func.return_type))
        lines.append("")

    return "\n".join(lines)


def render_class(cls: ClassInfo) -> str:
    """Render documentation for a single class.

    Produces a heading, class signature, description, method list,
    and detailed method documentation.

    Args:
        cls: The class info.

    Returns:
        Formatted markdown for the class.
    """
    bases = "({})".format(", ".join(cls.base_classes)) if cls.base_classes else ""

    lines = [
        "#### `{}`".format(cls.name),
        "",
        "```",
    ]

    if cls.decorators:
        for dec in cls.decorators:
            lines.append("@{}".format(dec))

    lines.append("class {}{}".format(cls.name, bases))
    lines.append("```")
    lines.append("")

    lines.append("{} | Lines {}-{}".format(
        _visibility_badge(cls.visibility),
        cls.start_line,
        cls.end_line,
    ))
    lines.append("")

    lines.append(_docstring_summary(cls.docstring))
    lines.append("")

    if cls.docstring and len(cls.docstring.strip().splitlines()) > 1:
        lines.append("<details>")
        lines.append("<summary>Full Documentation</summary>")
        lines.append("")
        lines.append("```")
        lines.append(cls.docstring.strip())
        lines.append("```")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Methods summary table
    if cls.methods:
        lines.append("**Methods:**")
        lines.append("")
        lines.append("| Method | Visibility | Static | Class Method |")
        lines.append("|---|---|---|---|")
        for m in cls.methods:
            lines.append("| `{}` | {} | {} | {} |".format(
                m.name,
                m.visibility.value,
                "Yes" if m.is_static else "-",
                "Yes" if m.is_classmethod else "-",
            ))
        lines.append("")

        # Detailed method docs
        for m in cls.methods:
            lines.append(render_method(m))

    return "\n".join(lines)


def render_method(method: MethodInfo) -> str:
    """Render documentation for a single class method.

    Args:
        method: The method info.

    Returns:
        Formatted markdown for the method.
    """
    sig = _format_param_signature(method.parameters)
    ret = " -> {}".format(method.return_type) if method.return_type else ""

    lines = [
        "##### `{}`".format(method.name),
        "",
        "```",
    ]

    if method.decorators:
        for dec in method.decorators:
            lines.append("@{}".format(dec))

    lines.append("{}{}{}".format(method.name, sig, ret))
    lines.append("```")
    lines.append("")

    lines.append(_docstring_summary(method.docstring))
    lines.append("")

    if method.parameters:
        lines.append("| Name | Type | Default |")
        lines.append("|---|---|---|")
        for p in method.parameters:
            type_str = "`{}`".format(p.type_hint) if p.type_hint else "-"
            default_str = "`{}`".format(p.default_value) if p.default_value else "-"
            lines.append("| `{}` | {} | {} |".format(p.name, type_str, default_str))
        lines.append("")

    if method.return_type:
        lines.append("**Returns:** `{}`".format(method.return_type))
        lines.append("")

    return "\n".join(lines)


def render_dependency_section(analysis: AnalysisResult) -> str:
    """Render the dependency analysis section.

    Args:
        analysis: The full analysis result.

    Returns:
        Formatted markdown for the dependency overview.
    """
    graph = analysis.dependency_graph
    lines = [
        "---",
        "",
        "## Dependency Analysis",
        "",
    ]

    # Internal dependencies
    internal_edges = [e for e in graph.edges if e.is_internal]
    if internal_edges:
        lines.append("### Internal Dependencies")
        lines.append("")
        lines.append("| Source | Target | Imported Names |")
        lines.append("|---|---|---|")
        for edge in internal_edges:
            names = ", ".join(edge.imported_names) if edge.imported_names else "(entire module)"
            lines.append("| `{}` | `{}` | {} |".format(
                edge.source, edge.target, names
            ))
        lines.append("")

    # External dependencies
    if graph.external_deps:
        lines.append("### External Dependencies")
        lines.append("")
        for dep in sorted(graph.external_deps):
            lines.append("- `{}`".format(dep))
        lines.append("")

    return "\n".join(lines)


def render_inheritance_section(analysis: AnalysisResult) -> str:
    """Render the class inheritance hierarchy section.

    Args:
        analysis: The full analysis result.

    Returns:
        Formatted markdown for the inheritance overview.
    """
    tree = analysis.inheritance_tree
    if not tree.nodes:
        return ""

    lines = [
        "---",
        "",
        "## Class Hierarchy",
        "",
    ]

    # Only show classes that participate in inheritance
    has_hierarchy = False
    for fq_name, node in tree.nodes.items():
        if node.base_classes or node.subclasses:
            has_hierarchy = True
            short_name = fq_name.rsplit(".", 1)[-1]
            bases = ", ".join(node.base_classes) if node.base_classes else "none"
            subs = ", ".join(
                s.rsplit(".", 1)[-1] for s in node.subclasses
            ) if node.subclasses else "none"
            lines.append("- **{}** (depth: {})".format(short_name, node.depth))
            lines.append("  - Inherits from: {}".format(bases))
            lines.append("  - Subclassed by: {}".format(subs))
            lines.append("  - Defined in: `{}`".format(fq_name.rsplit(".", 1)[0]))
            lines.append("")

    if not has_hierarchy:
        lines.append("No inheritance relationships detected.")
        lines.append("")

    return "\n".join(lines)
